name: Gibsons League API

on:
  push:
    paths:
      - src/server/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'src/server/GibsonsLeague.Api/appsettings.json'
      env:
        ConnectionStrings.GibsonsLeagueDb: ${{ secrets.GLA_DB_CONNECTIONSTRING }}
        Yahoo.ClientSecret: ${{ secrets.GLA_YAHOOAPPSECRET }}
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build src/server/. -f src/server/GibsonsLeague.Api/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/gibsonsleague:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/gibsonsleague:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/gibsonsleague:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/gibsonsleague:latest
